require('babel-register')
const express = require('express')
const morgan = require('morgan')
const mongoose = require('mongoose')
const fs = require('fs')
const cors = require('cors')
const _ = require('lodash')
const bodyParser = require('body-parser')
const React = require('react')
const ReactDOMServer = require('react-dom/server')
const ReactRouter = require('react-router')
const ReactRedux = require('react-redux')
const baseTemplate = fs.readFileSync('./public/index.html')
const template = _.template(baseTemplate)
const { match, RouterContext } = require('react-router')
const { Provider } = require('react-redux')
const { port, dev, prod, database, Injector, Access } = require('./server/config/main')
const app = express()

app
  .use('/public', express.static('./public'))
  .use(cors())
  .use(bodyParser.urlencoded({extended: false}))
  .use(bodyParser.json())
  .use(morgan('dev'))
  .use(Access())
  .use(Injector())
  .use(prod)

mongoose.connect(database)
app.listen(process.env.PORT || port, () => (console.log(`server is now up on port: ${port}`)))
